//#define AS_DEBUG
//__pragma(optimize("",off))

#include "UObject/Script.h"
#include "StartAngelscriptHeaders.h"
#include "AngelscriptInclude.h"

#include "as_atomic.cpp"
#include "as_builder.cpp"
#include "as_bytecode.cpp"
#include "as_callfunc.cpp"
#include "as_compiler.cpp"
#include "as_configgroup.cpp"
#include "as_context.cpp"
#include "as_datatype.cpp"
#include "as_gc.cpp"
#include "as_generic.cpp"
#include "as_globalproperty.cpp"
#include "as_memory.cpp"
#include "as_module.cpp"
#include "as_objecttype.cpp"
#include "as_outputbuffer.cpp"
#include "as_parser.cpp"
#include "as_scriptcode.cpp"
#include "as_scriptengine.cpp"
#include "as_scriptfunction.cpp"
#include "as_scriptnode.cpp"
#include "as_scriptobject.cpp"
#include "as_string.cpp"
#include "as_string_util.cpp"
#include "as_thread.cpp"
#include "as_tokenizer.cpp"
#include "as_typeinfo.cpp"
#include "as_variablescope.cpp"
#include "EndAngelscriptHeaders.h"